parent=keycloak
import=common/keycloak

styles=css/login.css
scripts=js/login.js

kcHtmlClass=
kcBodyClass=si-login-body
kcLoginClass=si-login-container

kcLoginCardClass=si-card
kcFormHeaderClass=si-form-header
kcFormGroupClass=si-form-group
kcLabelClass=si-label
kcInputClass=si-input
kcInputWrapperClass=si-input-wrapper
kcButtonClass=si-btn
kcButtonPrimaryClass=si-btn-primary
kcButtonLargeClass=si-btn-large
kcButtonBlockClass=si-btn-block
kcButtonDefaultClass=si-btn-default
kcFeedbackErrorIcon=si-error-icon
kcAlertClass=si-alert
kcAlertErrorClass=si-alert-error
kcAlertInfoClass=si-alert-info
kcAlertWarningClass=si-alert-warning
kcAlertSuccessClass=si-alert-success

displayInfo=true
displayWide=false
